version: '3'

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: always 
        volumes:  
            - ../:/var/www/html
            - ./nginx/conf/conf.d:/etc/nginx/conf.d
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - php73-fpm
            - php74-fpm
            - php80-fpm
        links:
            - php73-fpm
            - php74-fpm
            - php80-fpm
        ports:  
            - 80:80/tcp
            - 443:443/tcp
        network_mode: bridge

    php80-fpm:
        image: bincent/php:8.0-fpm-alpine
        container_name: php80-fpm
        restart: always 
        volumes:  
            - ../:/var/www/html
            - ./php-fpm/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./php-fpm/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
        network_mode: bridge

    php74-fpm:
        image: bincent/php:7.4-fpm-alpine
        container_name: php74-fpm
        restart: always
        volumes:
            - ../:/var/www/html
            - ./php-fpm/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./php-fpm/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
        network_mode: bridge

    php73-fpm:
        image: bincent/php:7.3-fpm-alpine
        container_name: php73-fpm
        restart: always 
        volumes:  
            - ../:/var/www/html
            - ./php-fpm/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./php-fpm/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
        network_mode: bridge